all: substr cicle

substr: lr4_1.o
	g++ lr4_1.o -o substr -std=c++11
cicle: lr4_2.o
	g++ lr4_2.o -o cicle -std=c++11
lr4_1.o: lr4_1.cpp
	g++ -c lr4_1.cpp -std=c++11
lr4_2.o: lr4_2.cpp
	g++ -c lr4_2.cpp -std=c++11
