all: greedy a_star

greedy: lab2_1.o
	g++ lab2_1.o -o greedy -std=c++11
a_star: lab2_2.o
	g++ lab2_2.o -o a_star -std=c++11
lab2_1.o: lab2_1.cpp
	g++ -c lab2_1.cpp -std=c++11
lab2_2.o: lab2_2.cpp
	g++ -c lab2_2.cpp -std=c++11