all: l2_2.exe l2_1.exe

l2_2.exe: l2_2.o
	g++ l2_2.o -o l2_2 -std=c++11
l2_1.exe: l2_1.o
	g++ lab2_2.o -o l2_1 -std=c++11
l2_2.o: l2_2.cpp
	g++ -c l2_2.cpp -std=c++11
l2_1.o: l2_1.cpp
	g++ -c l2_1.cpp -std=c++11
