KEYS=-Wall -Wextra

all: aStar.o
	g++ aStar.o -o aStar.exe $(KEYS)
aStar.o: aStar.cpp
	g++ -c aStar.cpp -o aStar.o

jadina: jadina.o
	g++ jadina.o -o Jadina.exe $(KEYS)
jadina.o: jadina.cpp
	g++ -c jadina.cpp -o jadina.o